version: '2'
services:
    monolith-app:
        image: monolith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://monolith-postgresql:5432/monolith
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monolith-postgresql:
        extends:
            file: postgresql.yml
            service: monolith-postgresql
