version: '2'
services:
    monolith-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/monolith/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=monolith
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
